version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
      - DATABASE_URL=postgres://docker:ignite@localhost:5432/rentx # Você pode definir a URL do banco de dados aqui
    volumes:
      - pgdata:/data/postgres
    networks:
      - default

  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - default

volumes:
  pgdata:
    driver: local
